version: 2

models:
  - name: dim_fhv_trips
    description: ""
    columns:
      - name: dispatching_base_num
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: month
        data_type: int64
        description: ""

      - name: pulocationid
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dolocationid
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: sr_flag
        data_type: float64
        description: ""

      - name: affiliated_base_number
        data_type: string
        description: ""

  - name: fct_fhv_monthly_zone_traveltime_p90
    description: ""
    columns:
      - name: dispatching_base_num
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: month
        data_type: int64
        description: ""

      - name: pulocationid
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dolocationid
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: sr_flag
        data_type: float64
        description: ""

      - name: affiliated_base_number
        data_type: string
        description: ""

      - name: trip_duration
        data_type: int64
        description: ""

      - name: trip_duration_p90
        data_type: float64
        description: ""

  - name: fct_taxt_trips_monthly_fare_p95
    description: ""
    columns:
      - name: service_type
        data_type: string
        description: ""

      - name: year
        data_type: int64
        description: ""

      - name: month
        data_type: int64
        description: ""

      - name: p97
        data_type: float64
        description: ""

      - name: p95
        data_type: float64
        description: ""

      - name: p90
        data_type: float64
        description: ""

  - name: dim_monthly_zone_revenue
    description: ""
    columns:
      - name: revenue_zone
        data_type: string
        description: ""

      - name: revenue_month
        data_type: timestamp
        description: ""

      - name: service_type
        data_type: string
        description: ""

      - name: revenue_monthly_fare
        data_type: numeric
        description: ""

      - name: revenue_monthly_extra
        data_type: numeric
        description: ""

      - name: revenue_monthly_mta_tax
        data_type: numeric
        description: ""

      - name: revenue_monthly_tip_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_tolls_amount
        data_type: numeric
        description: ""

      - name: revenue_monthly_ehail_fee
        data_type: numeric
        description: ""

      - name: revenue_monthly_improvement_surcharge
        data_type: numeric
        description: ""

      - name: revenue_monthly_total_amount
        data_type: numeric
        description: ""

      - name: total_monthly_trips
        data_type: int64
        description: ""

      - name: avg_monthly_passenger_count
        data_type: float64
        description: ""

      - name: avg_monthly_trip_distance
        data_type: numeric
        description: ""

  - name: fct_taxi_trips_quarterly_revenue
    description: ""
    columns:
      - name: service_type
        data_type: string
        description: ""

      - name: year_quarter
        data_type: string
        description: ""

      - name: revenue_quarterly_total_amount
        data_type: numeric
        description: ""

      - name: previous_revenue_quarterly_total_amount
        data_type: numeric
        description: ""

      - name: qoq_growth
        data_type: numeric
        description: ""

  - name: fact_trips
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: service_type
        data_type: string
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_locationid
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dropoff_locationid
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""

      - name: payment_type_description
        data_type: string
        description: ""

  - name: dim_zones
    description: ""
    columns:
      - name: locationid
        data_type: int64
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: zone
        data_type: string
        description: ""

      - name: service_zone
        data_type: string
        description: ""